export enum NavigationRoutes {
  SplashScreen = 'SPLASHSCREEN',
  DashBoardDrawer = 'DASHBORADDRAWER',
  CreateUserScreen = 'CREATEUSERSCREEN',
  VideoScreen = 'VIDEOSCREEN',
  ProfileScreen = 'PROFILESCREEN',
  HomeStack = 'HOMESTACK',
  NotificationScreen = 'NOTIFICATIONSCREEN',
  HomeScreen = 'HOMESCREEN',
  SettingsScreen = 'SETTINGSSCREEN',
  DetailsScreen = 'DETAILSSCREEN',
  LoginScreen = 'LOGINSCREEN',
  SignUpScreen = 'SIGNUPSCREEN',
  HomeTabs = 'HOMETABS',
}
