export default {
  loginBtnText: 'LOGIN',
  logout: 'Logout',
  addUser: 'Add User',
  cancelBtn: 'Cancel',
  yes: 'Yes',
  saveChanges: 'Save Changes',
  splashScreenMessage: 'Loading Awesomeness...!',
  loginToContinue: 'Login to Continue',
  welcomeMessage: 'Welcome to UserHub',
  home: 'Home',
  userDetails: 'User details',
  register: 'Sign Up',
  notAUser: 'Not a user? Sign up',
  signUp: 'Signup to continue',
  alreadyUser: 'Already registered? Login',
  invalidCredentials: 'Invalid credentials !',
  dataSavedSuccessfully: 'Data saved sucessfully !',
  someThingWentWrong: 'Something went wrong!',
  loginErrorMessage: 'Your credentials may be invalid !',
  deleteConfirmationHeader: 'Are you sure?',
  deleteConfirmationMessage: 'You really want to delete this user?',
  searchUser: 'Search here...',
  emptyString: '',
  yupErrors: {
    emailError: 'Please enter valid email',
    passwordEmpty: 'Please enter your password',
    passwordInvalid:
      'Password must contain at least 8 characters, one uppercase, one number and one special case character',
    nameInvalid: 'Please enter valid name',
  },
  formInputNames: {
    firstName: 'firstName',
    lastName: 'lastName',
    email: 'email',
    password: 'password',
  },
  bottomNavigationTitles: {
    home: 'Home',
    create: 'Create',
    videos: 'Videos',
    profile: 'Profile',
  },
  editProfile: 'Edit Profile',
  opacity: 'AA',
  phone: '909900909',
  sendSms: 'sms:+909900909',
  screenTitles: {
    notifications: 'Notifications',
    settings: 'Settings',
    create: 'Create User',
    videos: 'Videos',
    profile: 'Your Profile',
  },
  defaultImg:
    'https://cdn.vectorstock.com/i/preview-1x/77/30/default-avatar-profile-icon-grey-photo-placeholder-vector-17317730.jpg',
  profilePictureModalText: 'Profile photo',
  gallery: 'Gallery',
  camera: 'Camera',
  avatar: 'Avatar',
  featureUnavaible: 'This Feature Unavailble/Unsupported on your device!',
  android: 'ANDROID',
  ios: 'IOS',
  permissions: 'PERMISSIONS',
  weNeedPermission: 'you need to provide permissions to use this feature!',
  providePermission: 'Provide Permission',
  videosEndpoint:
    'https://gist.githubusercontent.com/deepakpk009/99fd994da714996b296f11c3c371d5ee/raw/28c4094ae48892efb71d5122c1fd72904088439b/media.json',
  http: 'http',
  https: 'https',
  slash: '/',
  colons: ':',
  subscribe: 'Subscribe',
  like: 'Like',
  share: 'share',
  liveChat: 'Live chat',
  pipe: '|',
  commentTitle: 'Comments',
  comment: 'I liked this video very much. Amazing content! keep it up',
  settings: 'Settings',
  appVersion: 'Version 7.0',
  searchEmpty: 'No results found!',
};
